; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32-C3-ROS

[env:esp32-C3-ROS]
platform = espressif32
board = lolin_c3_mini
framework = arduino

build_flags = 
  ;-DARDUINO_USB_CDC_ON_BOOT=1
  ;-DARDUINO_USB_MODE=1
  ;-DBOARD_HAS_PSRAM
  ;-DDEBUG
  -DCORE_DEBUG_LEVEL=5    ; 0 None, 1 Error, 2 Warn, 3 Info, 4 Debug, 5 Verbose
  -DONBOARD_LED_PIN=8
  -DVR_TX_PIN=4
  -DVR_RX_PIN=3
  -I include

board_microros_distro = jazzy
board_microros_transport = serial

monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0


lib_ldf_mode = deep+

lib_deps =
  plerup/EspSoftwareSerial
  https://github.com/micro-ROS/micro_ros_platformio
;        https://github.com/AvansMechatronica/micro_ros_platformio

[env:esp32-C3-ROS-WiFi]
platform = espressif32
board = lolin_c3_mini
framework = arduino

board_build.filesystem = littlefs ; only needed for WIFI_CONFIG_AP, but it is needed for the WROOM, so we disable it for now. It can be enabled if needed.

build_flags = 
	-DWIFI  
;	-DWIFI_CONFIG_AP
;	-DWIFI_SSID=\"your_ssid\"
;	-DWIFI_PASSWORD=\"your_password\"
;	-DAGENT_IP_ADDRESS=\"192.168.2.150\"
  ;-DARDUINO_USB_CDC_ON_BOOT=1
  ;-DARDUINO_USB_MODE=1
  ;-DBOARD_HAS_PSRAM
  ;-DDEBUG
  -DCORE_DEBUG_LEVEL=5    ; 0 None, 1 Error, 2 Warn, 3 Info, 4 Debug, 5 Verbose
  -DONBOARD_LED_PIN=8
  -DVR_TX_PIN=4
  -DVR_RX_PIN=3
  -I include

board_microros_distro = jazzy
board_microros_transport = wifi

monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0


lib_ldf_mode = deep+

lib_deps =
  plerup/EspSoftwareSerial
  https://github.com/micro-ROS/micro_ros_platformio
;        https://github.com/AvansMechatronica/micro_ros_platformio
